# Generated by Django 5.2.7 on 2026-02-12 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Cliente Ativo?'),
        ),
    ]
