# Generated by Django 5.2.7 on 2026-02-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(default='', max_length=10, verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='eh_deficiente',
            field=models.BooleanField(default=False, verbose_name='É Pessoa com Deficiência?'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nacionalidade',
            field=models.CharField(default='Brasileira(o)', max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(default='', max_length=10, verbose_name='Número'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='orgao_expeditor',
            field=models.CharField(default='SSP/BA', max_length=20, verbose_name='Órgão Expeditor (Ex: SSP/BA)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(max_length=255, verbose_name='Rua / Logradouro'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
